elites-twitter/config/routes.rb
Rails.application.routes.draw do
  
  root 'tweets#index'
  get 'tweets/index'
  devise_for :users
  #resources :tweets
  resources :users, :only => [:show]
  
  resources :tweets do
    collection do
      match 'search' => 'tweets#search', via: [:get, :post], as: :search
    end
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

elites-twitter/app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 140 }
  
  scope :with_keywords, -> keywords {
    if keywords.present?
      columns = [:content]
      where(keywords.split(/[[:space:]]/).reject(&:empty?).map {|keyword|
        columns.map { |a| arel_table[a].matches("%#{keyword}%") }.inject(:or)
      }.inject(:and))
    end
  }
end

elites-twitter/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :tweets
         
  validates :name, presence: true, length: { minimum: 8 }, uniqueness: true
  validates_email_format_of :email, uniqueness: true, :message => '正しいメールアドレスの形式で入力してください。'
  validates :image, presence: true
  validates :profile, presence: true
  
  mount_uploader :image, UserThumbnailUploader
end

elites-twitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :set_global_search_variable

  def set_global_search_variable
    @q = nil
    @errors = params[:errors] if params[:errors].present?
    puts "************errors: #{@errors.first}" if params[:errors].present?
    @tweets = Tweet.all.order('updated_at DESC').page(params[:page])
    @tweet_input = Tweet.new(content: params[:content]) 
    keyword = "#{params.dig(:q, :keywords)}"
    
    @q = Tweet.with_keywords(params.dig(:q, :keywords)).ransack(params[:q])
    user = User.find_by_name(params.dig(:q, :keywords))
    if @q.present? || user.present?
      if @q.result.present? && user.present? 
        @tweets = @q.result.page(params[:page])
        @tweets = user.tweets.page(params[:page])
      elsif @q.result.present? 
        @tweets = @q.result.order('updated_at DESC').page(params[:page])
      elsif user.present?
        @tweets = user.tweets.order('updated_at DESC').page(params[:page])
      else
        @tweets = nil
      end
    end
  end
  
  def after_sign_in_path_for(resource)
    tweets_index_path
  end
  
  def after_sign_out_path_for(resource)
    new_user_session_path
  end
  
  protected
  
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path, :notice => 'ログインをしてください。'
      ## if you want render 404 page
      ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
    end
  end
    
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:image])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:profile])
    
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:profile])
  end
  
end

elites-twitter/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  # def new
  #   super
  # end
  
  # def create
  #     super #Nothing special here.
  #   end
  
  # def update
  #   super
  # end
  
  # def after_sign_up_path_for(resource)
  #   after_sign_in_path_for(resource)
  # end
  
  # protected
  
  # def sign_up(resource_name, resource)
  #   false
  # end
  
end

elites-twitter/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  
  def search
    index
    render :index
  end
  
  def index
  end
  
  def create
    tweet = Tweet.new
    tweet.attributes = tweet_input_param
    tweet.user_id = current_user.id
    
    if tweet.valid? # バリデーションチェック
      tweet.save!
      flash[:notice] = "投稿しました"
      if tweet.reply_tweet_id.present?
        redirect_to action: :show, :id => tweet.reply_tweet_id
      else
        redirect_to action: :index
      end
    else
      flash[:alert] = tweet.errors.full_messages
      if tweet.reply_tweet_id.present?
        redirect_to action: :show, :id => tweet.reply_tweet_id, content: tweet.content, errors: tweet.errors.full_messages
      else
        redirect_to action: :index, content: tweet.content, errors: tweet.errors.full_messages
      end
    end
  end
  
  def edit
    @tweet_input = Tweet.find(params[:id])
    if current_user.id != @tweet_input.user_id
      redirect_to action: :index, errors: ["自分以外のツイートは編集・削除できません。"]
    end
    @tweet_input.content = params[:content] if params[:content].present?
    if params[:errors].present?
      puts '***************errors exist in error'
      @errors = params[:errors] 
      puts @errors.first
      params[:content] = nil
    end
  end
  
  def update
    puts '***************** update'
    @tweet_input = Tweet.find(params[:id])
    @tweet_input.attributes = tweet_input_param
    @tweet_input.user_id = current_user.id
    if @tweet_input.valid? # バリデーションチェック
      @tweet_input.save!
      flash[:notice] = "更新しました"
      redirect_to action: :index
    else
      flash[:alert] = @tweet_input.errors.full_messages
      redirect_to action: :edit, content: @tweet_input.content, errors: @tweet_input.errors.full_messages
    end
  end
  
  def show
    @current_user = User.find(current_user.id)
    @tweet = Tweet.find(params[:id])
    @reply_tweets = Tweet.where(["reply_tweet_id = ?", @tweet.id]).order('updated_at DESC').page(params[:page])
    
    #reply
    @tweet_input = Tweet.new(content: params[:content]) 
    # @errors = params[:errors] if params[:errors].present?
    
  end
  
  def destroy
    @tweet_input = Tweet.find(params[:id])
    @tweet_input.destroy
    flash[:notice] = "削除しました"
    redirect_to action: :index
  end
  
  private
  def tweet_input_param
    params.require(:tweet).permit(:user_id, :reply_tweet_id, :content)
  end
end

elites-twitter/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @tweets = User.find(params[:id]).tweets.order('updated_at DESC').page(params[:page])
    @user = User.find(params[:id])
  end
end

elites-twitter/app/helpers/application_helper.rb
module ApplicationHelper
end

elites-twitter/app/helpers/tweets_helper.rb
module TweetsHelper
end

elites-twitter/app/helpers/users_helper.rb
module UsersHelper
end

elites-twitter/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to tweets_index_path, class: "navbar-brand" do%>
          <i class="fa fa-twitter right-margin" aria-hidden="true"></i>Twitter
        <% end %>
      </div>
  
      <div class="collapse navbar-collapse" id="navbar-collapse-menu">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.email, user_path(current_user.id) %></li>
            <li class="hidden-xs search"><%= render 'tweets/search' %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "ログイン", new_user_session_path %></li>
            <li><%= link_to "新規登録", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

elites-twitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElitesTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/header'%>
  <div class="row">
    <div class="search_for_mobile col-xs-10 col-xs-offset-1 hidden-sm hidden-md hidden-lg">
      <%= render 'tweets/search' %>
      <div class="col-xs-offset-1"></div>
    </div>
  </div>
  <% if notice.present? %>
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= notice %></p>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0">
      <%= yield %>
   </div>
  </div>

</body>
</html>

elites-twitter/app/views/tweets/_form.html.erb
<!-- エラーメッセージ -->
<% if @errors.present? %>
  <div class="error">
    <% @errors.each do |message| %>
      <p class="alert"><%= message %></p>
    <% end %>
  </div>
<% end %>

<div class="form-group">
  <div>
    <%= f.text_area :content, :value => @tweet_input.try(:content), class: 'form-control', placeholder: "（本文は１４０字以内で投稿）", rows: 3 %>
  </div>
</div>
    

elites-twitter/app/views/tweets/_link_to_tweet_show.html.erb
<div class="col-xs-3 col-sm-2 col-md-2 show clearfix">
  <%= link_to "詳細", tweet_path(tweet), class: "btn btn-primary show_btn img-responsive pull-right" %>
</div>

elites-twitter/app/views/tweets/_post_tweet.html.erb
<%= form_for(@tweet_input, :url => {:action => 'create'} ) do |f| %>
  <div class="post_tweet">
    <%= render :partial => 'tweets/form', :locals => {:f => f} %>
    <div class="actions form-group">
      <%= f.submit class: 'btn btn-primary submit_btn' %>
    </div>
</div>
   
  <div class="clearfix"></div>
<% end %>

elites-twitter/app/views/tweets/_search.html.erb
<%# form_for の代わりに search_form_for を使うことで検索フォームを作成 %>
<%= search_form_for @q, url: search_tweets_path, html: { method: :post }  do |f| %>

  <%# start 特定の文字列で始まる商品名で検索 %>
  <div class="clearfix">
    <span class="fa fa-search errspan"></span>
    <%= f.text_field :keywords, required: false, value: params.dig(:q, :keywords), class: 'form-control', placeholder: "キーワードまたはユーザー検索", size: "30"  %>
  </div>
  
<% end %>
<hr />

elites-twitter/app/views/tweets/_thumbnail.html.erb
<!-- サムネイルの設定確認 -->
<div class="thumbnail_img">
  <% if user.image? %>
      <%= link_to image_tag(user.image.url, :class => "img-responsive"), user_path(user), {:class => "link"} %>
  <% else %>
      NO IMAGE
  <% end %>
</div>

elites-twitter/app/views/tweets/_tweet_box.html.erb
<!--need div row each_tweet-->
<div class="img col-xs-2 col-sm-2 col-md-2">
  <%= render :partial => 'tweets/thumbnail', :locals => {:user => tweet.user} %>
</div>
<div class="col-xs-7 col-sm-8 col-md-8 information">
  <div class="row">
    <div class="tweet_name col-xs-12 col-sm-4 col-md-5"><%= link_to "@#{tweet.user.name}", user_path(tweet.user_id), { :class => "link" } %></div>
    <div class="tweet_created col-xs-12 col-sm-4 col-md-5">(<%= tweet.created_at %>)</div>
  </div>
  <div class="row">
    <% if current_user.id == tweet.user_id %>
      <%= link_to edit_tweet_path(tweet.id), { :class => "link col-xs-12 col-sm-12 col-md-12"}  do%>
        <div class="tweet_content"><%= tweet.content %></div>
      <% end %>
    <% else %>
      <div class = "col-xs-12 col-sm-12 col-md-12">
        <div class="tweet_content"><%= tweet.content %></div>
      </div>
    <% end %>
  </div>
</div>

elites-twitter/app/views/tweets/_tweets.html.erb
<div id="tweet_boxes">
  <% if @tweets.present? %>
    <%= page_entries_info @tweets %>
    <% @tweets.each do |tweet|%>
      <div class="row each_tweet">
        <%= render :partial => 'tweets/tweet_box', :locals => {:tweet => tweet} %>
        <%= render :partial => 'tweets/link_to_tweet_show', :locals => {:tweet => tweet} %>  
      </div>
    <% end %>
    <% if @tweets.present? %>
      <%= paginate @tweets %>
    <% end %>
  <% else %>
    ツイートがありません。
  <% end %>
</div>

elites-twitter/app/views/tweets/edit.html.erb
<!--tweets/edit.html.erb-->
<div class="wrapper edit_page">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0">
      <h2><i class="fa fa-pencil" aria-hidden="true"></i>ツイート編集画面</h2>
      <div class="show_page_error"></div>
      <%= form_for(@tweet_input, :url => {:action => 'update'} ) do |f| %>
        <%= render :partial => 'tweets/form', :locals => {:f => f} %>
        <div class="actions form-group">
          <%= f.submit class: 'btn btn-primary submit_btn'%>
        </div>
      <% end %>
      <%= button_to "削除", { :action => "destroy", :id => @tweet_input.id }, :class=>"btn btn-danger delete_btn clearfix", data: {:confirm => "本当に削除しますか?"}, :method => :delete %>
    </div>
  </div>
</div>

elites-twitter/app/views/tweets/index.html.erb
<!--tweets/index.html-->
<div class="wrapper index_page">
  <div class="show_page_error"></div>
  <%= render 'post_tweet'%>
  <%= render 'tweets' %>
</div>

elites-twitter/app/views/tweets/show.html.erb
<!--tweets/show.html.erb-->
<div id="tweet_box" class="wrapper show_page">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <%= render :partial => 'tweets/tweet_box', :locals => {:tweet => @tweet} %>
    </div>
  </div>
      
  <div class=" top-buffer">
    <%= page_entries_info @reply_tweets %>
    <% if @reply_tweets.present? %>
      <% @reply_tweets.each do |tweet|%>
        <div class="reply row">
          <div class="col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-xs-11 col-sm-11 col-md-11">
            <%= render :partial => 'tweets/tweet_box', :locals => {:tweet => tweet} %>
            <%= render :partial => 'tweets/link_to_tweet_show', :locals => {:tweet => tweet} %>  
          </div>
        </div>
      <% end %>
      <%= paginate @reply_tweets %>
   
    <% end %>
  </div>
        
      <!--reply to tweet-->
  <div class="reply row lg-top-buffer">
    <div class="col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-xs-11 col-sm-11 col-md-11">
      <div class=""><h3>返信する</h3></div>
      <div class="row">
        <div class="img col-xs-3 col-sm-3 col-md-3">
          <%= render :partial => '/tweets/thumbnail', :locals => {:user => @current_user} %>
          
        </div>
        <div class="col-xs-6 col-sm-7 col-md-7">
          <%= form_for(@tweet_input, :url => {:action => 'create'} ) do |f| %>
            <div class="post_tweet">
              <%= render :partial => 'form', :locals => {:f => f} %>
                <%= f.hidden_field :reply_tweet_id, :value => params[:id] %>
                <div class="show_page_error pull-left"></div>
                <div class="actions form-group">
                  <%= f.submit "返信", class: 'btn btn-primary submit_btn' %>
                </div>
            </div>
          </div>
          <div class="clearfix"></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

elites-twitter/app/views/users/show.html.erb
<!--users/show.html.erb-->
<div id="tweet_boxes" class="wrapper show_user_page">
  <div class="row user_profile">
    <div class="col-xs-3 col-sm-2 col-md-2 profile_pic">
      <%= render :partial => '/tweets/thumbnail', :locals => {:user => @user} %>
    </div>
    <div class="col-xs-8 col-sm-8 col-md-8 contents">
      <div class="row">
        <div class="profile_name col-sm-4 col-md-4">@<%= @user.name  %></div>
        <div class="last_login col-sm-8 col-md-8">最終ログイン日：<%= @user.last_sign_in_at %></div>
        <div class="col-md-12 top-buffer">プロフィール</div>
        <div class="profile_content col-md-12 top-buffer"><%= @user.profile %>
        </div>
      </div>
    </div>
  </div>
  <div class="lg_top_buffer" style="margin-top: 50px">
    <%= render 'tweets/tweets'%>
  </div>
</div>